apiVersion: v1
kind: Pod
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  containers:
    - name: hello-node
      image: spursyy/hello-node
      imagePullPolicy: Always
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: myregistrykey
  
